[package]
name = "cp"
version = "0.1.0"
edition = "2024"
default-run = "solution"

[[bin]]
name = "solution"
path = "src/main.rs"

[[bin]]
name = "check"
path = "src/bin/check.rs"

[dependencies]
colored = "3.0.0"

